import type { Metadata } from 'next';
import './globals.scss';
import './reset.css';
import React from 'react';

export const metadata: Metadata = {
  title: 'DBLand',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
