import './globals.css';
import './reset.css';
import './theme.scss';
import React from 'react';
import { theme } from './theme';

// export const metadata: Metadata = {
//   title: 'DBLand',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body>
    {/*<CssVarsProvider theme={theme}>*/}
      {children}
    {/*</CssVarsProvider>*/}
    </body>
    </html>
  );
}
